SOLVER:
  BATCH_SIZE: 48
  MAX_EPOCH: 200
  LR: 4e-5
  SEED: 42

DA:
  TASK: False
  USE: False

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "TRANSGAT_Vanilla"
  TAG: "Non_DA"

